"""empty message

<<<<<<< HEAD:migrations/versions/7d0bdad715f7_.py
Revision ID: 7d0bdad715f7
Revises: 
Create Date: 2021-05-19 22:14:35.641144
=======
Revision ID: aa35e639aa71
Revises: 
Create Date: 2021-05-19 19:20:55.630648
>>>>>>> 8c9397c886fd71ff5cb2c0ac2dff52fc8d86a3c8:migrations/versions/aa35e639aa71_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/7d0bdad715f7_.py
revision = '7d0bdad715f7'
=======
revision = 'aa35e639aa71'
>>>>>>> 8c9397c886fd71ff5cb2c0ac2dff52fc8d86a3c8:migrations/versions/aa35e639aa71_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('money_send', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('transaction_code', sa.Integer(), nullable=False),
    sa.Column('money', sa.String(length=120), nullable=True),
    sa.Column('number_transfer', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('bank_payment', sa.String(length=120), nullable=False),
    sa.Column('account_number', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('card')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('administrator')
    # ### end Alembic commands ###
